package io.tanks.common.network.state;

public enum ClientStateType {
	LOADING_GAME, MAIN_MENU, OPTIONS_MENU, CREATE_LAN_GAME_MENU, JOIN_LAN_GAME_MENU, FIND_GAME_ONLINE_MENU, CREATING_MATCH, MATCH_INIT, WAITING_FOR_PLAYERS, ROUND_INIT, ROUND_START, ROUND, ROUND_END, LEAVING_MATCH, MATCH_END, EXIT_GAME
}